version: '3.5'

services:
    app:
        env_file:
            - ./.env
        build: docker/php/
        working_dir: ${WORKING_DIR}
        volumes:
            - ./:${WORKING_DIR}
        container_name: sonder_app
        links:
            - db

    webserver:
        image: nginx:alpine
        ports:
            - ${NGINX_PORT}:80
        working_dir: ${WORKING_DIR}
        volumes:
            - ./:${WORKING_DIR}
            - ./docker/nginx/config/conf.d/:/etc/nginx/conf.d/
        links:
            - app
        container_name: sonder_webserver

    db:
        image: mysql:8
        restart: always
        environment:
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        volumes:
            - mysql-volume:/var/lib/mysql
        container_name: sonder_db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sonder_phpmyadmin
        restart: always
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_HOST: sonder_db
            PMA_ARBITRARY: 1

volumes:
    mysql-volume:
