version: '3.5'

services:
    app:
        env_file:
            - ./.env
        build: docker/php/
        working_dir: ${WORKING_DIR}
        volumes:
            - ./:${WORKING_DIR}
        container_name: sonder_app

    webserver:
        image: nginx:alpine
        ports:
            - ${NGINX_PORT}:80
        working_dir: ${WORKING_DIR}
        volumes:
            - ./:${WORKING_DIR}
            - ./docker/nginx/config/conf.d/:/etc/nginx/conf.d/
        links:
            - app
        container_name: sonder_webserver

    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - ${DB_PORT}:5432
        volumes:
            - ./docker/database/volumes:/var/lib/postgresql/data
        container_name: sonder_db
